[theme]
name = "semi-native"
[icons]
name = "material-nf"
[[block]]
block = "disk_space"
path = "/home/t1m3runn3r2359"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "{icon} ~: {available} Free"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}/{mem_total}"
clickable = false

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"
[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min},{max},{average}ﱒ"
[[block]]
block = "pacman"
interval = 600
format = "{pacman} +{aur}"
format_up_to_date = ""
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "paru -Qua"

[[block]]
block = "net"
interval = 5
device = "wlo1"
format = "{speed_up} {speed_down}"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage} {time} hrs"

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}"
service = { name = "openweathermap", api_key = "f47f4069e6b2e0459e5a88e20efcd231", city_id = "140463", units = "metric" }

[[block]]
block = "sound"
max_vol = 200
headphones_indicator = true
on_click = "alacritty --class Alacritty,FTerm -e pulsemixer"

[[block]]
block = "keyboard_layout"
driver = "xkbswitch"
on_click = "xkb-switch -n"
interval = 1

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %H:%M:%S"
