
[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
# history = 10000
# multiplier = 3
opacity = 0.7
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 25

[window.padding]
x = 6
y = 6

[general]
live_config_reload = true
import = [ "/home/t1m3runn3r2359/.config/alacritty/fonts.toml"]
